{{- range $name, $customConfig := .Values.simulators }}
{{- $config := merge $customConfig $.Values.defaults }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-sim-scheme-adapter
  labels:
    app: {{ $name }}-sim
    chart: {{ template "mojaloop-simulator.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
data:
  {{- range $k, $v := $config.config.schemeAdapter.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-sim-backend
  labels:
    app: {{ $name }}-sim
    chart: {{ template "mojaloop-simulator.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
data:
  {{- range $k, $v := $config.config.simBackend.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
---
{{- end }}
