{{- range $name, $customConfig := .Values.simulators }}
{{- $config := merge $customConfig $.Values.defaults }}
{{- if $config.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sim-{{ $name }}
  labels:
    app: sim-{{ $name }}
    chart: {{ template "mojaloop-simulator.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
{{- with $config.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - http:
        paths:
        - path: /sim/{{ $name }}/dfsp(.*)
          backend:
            serviceName: sim-{{ $name }}
            servicePort: inboundapi
        - path: /sim/{{ $name }}/test(.*)
          backend:
            serviceName: sim-{{ $name }}
            servicePort: inboundapi
{{- end }}
---
{{ end }}
