{{- range $name, $customConfig := .Values.simulators }}
{{- $config := merge $customConfig $.Values.defaults }}
apiVersion: v1
kind: Service
metadata:
  name: sim-{{ $name }}
  labels:
    app: sim-{{ $name }}
    chart: {{ template "mojaloop-simulator.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
   type: ClusterIP
   ports:
     - port: 4000
       protocol: TCP
       name: inboundapi
       targetPort: inboundapi
     - port: 4001
       protocol: TCP
       name: outboundapi
       targetPort: outboundapi
     - port: 3002
       protocol: TCP
       name: reportapi
       targetPort: reportapi
     - port: 3003
       protocol: TCP
       name: testapi
       targetPort: testapi
   selector:
     app: sim-{{ $name }}
     release: {{ $.Release.Name }}
---
{{ end }}
